num_proc: 1
cache_dir: cache/       # Usually for raw and processed data
log_dir: logs/
ckpt_dir: ckpt/
run_id: InsCD  # Change this to your customized run id
rand_seed: 2024
reproducibility: True

max_seq_length: 10

train_batch_size: 1024
eval_batch_size: 1024
lr: 2e-3
weight_decay: 5e-4
warmup_steps: 10000
steps: ~
epochs: 20
max_grad_norm: 1.0      # None for no clipping, else a float value
eval_interval: 1        # Evaluate every n epochs
split_target: log
split_manner: hold_out
patience: 5
val_metric: "auc"
metrics: ["acc", "auc"]
test_size: 0.2
val_size: 0.1