# Hyperparametr for Cluseter
ae_hidden_dims: [512, 256, 128]
ae_latent_dim: 64
n_jobs: -1
beta: 1
lamda: 1
pretrained: True
cluster_lr: 0.0001

feat_dim: 512
emb_dim: 16
layers: 4
leak: 0.8
momentum: 0.8

# Hyperparametr for IF
hidden_dims: [512, 256]
dropout: 0.5
